services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

  review-manager:
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8450:8450"
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      HTTP_URL_DUX_MANAGER: ${HTTP_URL_DUX_MANAGER}
    depends_on:
      - postgres
    networks:
      - shared-network

volumes:
  postgres-data:

networks:
  shared-network:
    external: true
